# Generated by Django 4.2.4 on 2024-02-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_record_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
