# Generated by Django 4.2.4 on 2024-02-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feedback_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='first_name',
        ),
    ]
